-- The title and rental duration (which the database gives in days) for all films
-- having a title starting with =S= and rented for between four and six days
-- (inclusive). Order your results by decreasing rental duration and them by film
-- title.
